---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: parallels
    options:
      memory: 1024
      cpus: 2
lint:
  name: yamllint
platforms:
  - name: ubuntu18
    box: generic/ubuntu1804
  - name: centos7
    box: generic/centos7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
