---
- name: Converge
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: geerlingguy.php-versions
    - role: geerlingguy.php-mysql
    - role: osticket
